# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build_test ]
  pull_request:
    branches: [ build_test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install gcc-multilib g++-multilib
        
        cd /
        sudo mkdir ./valve
        cd ./valve
        sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
        sudo tar xvf ./steam-runtime-sdk_latest.tar.xz
        sudo mv steam-runtime-sdk_2013-09-05 steam-runtime
        sudo chown -R $(id -u):$(id -g) ./steam-runtime
        cd ./steam-runtime
        (echo 1; echo 1; echo Y; echo Y; echo Y) | ./setup.sh
        ./shell-i386.sh
        
        cd $GITHUB_WORKSPACE/mp/src
        ./createallprojects
        make -f everything.mak
        
