# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build_test ]
  pull_request:
    branches: [ build_test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        runtime: [ linux-x64 ]
        include:
          - runtime: linux-x64
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Update build environment
      run: |
        sudo apt-get update
        sudo apt-get install build-essential gcc gcc-multilib g++-multilib make build-essential linux-headers-$(uname -r)
          
    - name: Install and setup Steam runtime SDK tools
      run: |
        cd /
        sudo mkdir ./valve
        cd ./valve
        sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
        sudo tar xvf ./steam-runtime-sdk_latest.tar.xz
        sudo mv steam-runtime-sdk_2013-09-05 steam-runtime
        sudo chown -R $(id -u):$(id -g) ./steam-runtime
        cd ./steam-runtime
        (echo 3; echo 1; echo Y; echo Y; echo Y) | ./setup.sh
        ./shell-i386.sh
        
        echo Testing /valve dirs...
        pwd && ls
        cd /valve/steam-runtime/
        pwd && ls
        cd ./bin/../amd64/
        pwd && ls
        cd ./x86_64-unknown-linux-gnu/
        pwd && ls
        cd ./bin/
        pwd && ls
        echo Done.
        
    - name: Build all
      run: |
        cd $GITHUB_WORKSPACE/mp/src
        ./createallprojects
        make -f everything.mak
        
